jacobi:
	make -C jacobi/ profile
fft128:
	make -C fft/128/ profile
fft256:
	make -C fft/256/ profile
sgemm:
	make -C sgemm/ profile
barnes_hut:
	make -C barnes_hut/ profile
bfs:
	make -C bfs/ profile
pagerank:
	make -C pagerank/ profile
spgemm:
	make -C spgemm/ profile


all: jacobi fft128 fft256 sgemm barnes_hut bfs pagerank spgemm
