u10k8.mtx:
	xz -d -k u10k8.mtx.xz

wiki-Vote.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/wiki-Vote.tar.gz
	tar -xvzf wiki-Vote.tar.gz
	rm wiki-Vote.tar.gz
	mv wiki-Vote/wiki-Vote.mtx .
	rm -rf wiki-Vote/

offshore.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/Um/offshore.tar.gz
	tar -xvzf offshore.tar.gz
	rm offshore.tar.gz
	mv offshore/offshore.mtx .
	rm -rf offshore/

soc-Pokec.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/soc-Pokec.tar.gz
	tar -xvzf soc-Pokec.tar.gz
	rm soc-Pokec.tar.gz
	mv soc-Pokec/soc-Pokec.mtx .
	rm -rf soc-Pokec/

ljournal-2008.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/ljournal-2008.tar.gz
	tar -xvzf ljournal-2008.tar.gz
	rm ljournal-2008.tar.gz
	mv ljournal-2008/ljournal-2008.mtx .
	rm -rf ljournal-2008/


hollywood-2009.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/LAW/hollywood-2009.tar.gz
	tar -xvzf hollywood-2009.tar.gz
	rm hollywood-2009.tar.gz
	mv hollywood-2009/hollywood-2009.mtx .
	rm -rf hollywood-2009/


roadNet-CA.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/SNAP/roadNet-CA.tar.gz
	tar -xvzf roadNet-CA.tar.gz
	rm roadNet-CA.tar.gz
	mv roadNet-CA/roadNet-CA.mtx .
	rm -rf roadNet-CA/
	
road-central.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_central.tar.gz
	tar -xvzf road_central.tar.gz
	rm road_central.tar.gz
	mv road_central/road_central.mtx road-central.mtx # rename;
	rm -rf road_central/

road-usa.mtx:
	wget https://suitesparse-collection-website.herokuapp.com/MM/DIMACS10/road_usa.tar.gz
	tar -xvzf road_usa.tar.gz
	rm road_usa.tar.gz
	mv road_usa/road_usa.mtx road-usa.mtx # rename;
	rm -rf road_usa/
