
####################
# CHANGE ME: TESTS #
####################
# TESTS += $(call test-name,[mtx-a],[mtx-b],[tiles-x],[tiles-y],[pods-x],[pods-y])

TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,0)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,0)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,0)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,0)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,1)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,1)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,1)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,1)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,2)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,2)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,2)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,2)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,3)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,3)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,3)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,3)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,4)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,4)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,4)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,4)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,5)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,5)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,5)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,5)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,6)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,6)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,6)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,6)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,7)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,7)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,7)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,7)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,8)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,8)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,8)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,8)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,yes,9)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,yes,9)
TESTS += $(call test-name,email-Enron,email-Enron,16,8,4,2,no,9)
TESTS += $(call test-name,roadNet-CA,roadNet-CA,16,8,4,2,no,9)
