u7k1-link   := https://drive.google.com/uc?id=1KJsixsZKgkIuqOs5TceKAEOBvhPn6PCZ
u10k8-link  := https://drive.google.com/uc?id=1KJsixsZKgkIuqOs5TceKAEOBvhPn6PCZ
g7k1-link   := https://drive.google.com/uc?id=1U8ge3qZ5NTrC9ypvP-w1ct5xZzJ0PSTS
g10k8-link  := https://drive.google.com/uc?id=1uVMe5eb8ND1JNkVxIDTKQh_Ig08_Nobq
%.mtx:
	gdown $($*-link)

.PHONY: clean
clean:
	rm *.mtx


