u7k1-link   := https://drive.google.com/uc?id=17GY8qA_ObPz9IeV4rnCMAMbBKGmziiz4
u10k8-link  := https://drive.google.com/uc?id=1tQuEwDajCOXgCAyvPo3T7hSmGXMZCDNu
g7k1-link   := https://drive.google.com/uc?id=1eAhwjzMxGm1WVOmBoWePFWLGff4MPI1D
g10k8-link  := https://drive.google.com/uc?id=16PJPSBZ1hdYr4vWdp0UQPgmGNHfC5PcM
%.mtx:
	gdown $($*-link)

.PHONY: clean
clean:
	rm *.mtx


